const data = [
  {
    productType: "arduino",
    name: "UNO starter kit for beginners",
    price: "$24",
    productImg: "/arduino starter kit.jpg",
    features: [],
    id: "1",
  },
  {
    productType: "arduino",
    name: "Mastering basic Arduino",
    price: "$20",
    productImg: "/arduino book.jpg",
    features: [],
    id: "2",
  },
  {
    productType: "raspberry",
    name: "Raspberry Pi 4 Model B (8GB)",
    price: "$75",
    productImg: "/raspberry pi 4.jpg",
    features: [],
    id: "3",
  },
  {
    productType: "raspberry",
    name: "Raspberry Pi 400 ",
    price: "$70",
    productImg: "/raspberry pi 400.jpg",
    features: [],
    id: "4",
  },
  {
    productType: "raspberry",
    name: "Raspberry Pi Zero 2W",
    price: "$20",
    productImg: "/raspberry zero.jpg",
    features: [],
    id: "5",
  },
  {
    productType: "parts",
    name: "Jumper Wires (100)",
    price: "$50",
    productImg: "/Jumper wires.jpg",
    features: [],
    id: "6",
  },
  {
    productType: "parts",
    name: "Buzzer",
    price: "$6",
    productImg: "/Buzzer.jpg",
    features: [],
    id: "7",
  },
];

export default data;
